### PR TITLE
AppRun: Sort library symbols

### PR DESCRIPTION
**Pull request by lat9nq**
Currently the AppRun binary does not sort the symbols it finds. This causes it to sometimes consider a library to be an older version than it actually is, thus replace it with the bundled one that is older than the host libraries need.

Replace the binary with a patched one from lat9nq/AppImageKit-checkrt@7c8eb07d86938d51ace13532a021e854a6e607e4
which does sort the symbols before trying to replace it.

Fixes this issue on some systems like Arch Linux.

### CODE REVIEW

**Comment by lioncash** [comment]
Has this issue been reported upstream in any form?

**Comment by lat9nq** [comment]
No it doesn't look like it. Should I upstream this?

**Comment by lat9nq** [comment]
@lioncash Well, went ahead and upstreamed it. https://github.com/darealshinji/AppImageKit-checkrt/pull/18

I would still like to get this merged if it checks out, since I have no idea how active that repository is.

**Comment by lioncash** [comment]
Sounds good. Just wanted to make sure it's at least filed upstream so we potentially don't need to roll our own custom binaries in the future

**Review by lioncash — APPROVED** [review]

**Pull request merged**
